import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "BLS : Hello",
    description: "Generated by create next app",
};

export default function HelloLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>{children}</div>
    );
}
